theme: jekyll-theme-minimal
description: Rentals and other services in El Zonte
logo: https://raw.githubusercontent.com/gcomte/arentura/main/assets/logoTransparent.png
social:
  twitter: https://twitter.com/arentura1
